# Generated by Django 3.0.2 on 2020-02-04 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biddingtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Typename', models.TextField()),
                ('TypeDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DateofBorth', models.DateField(max_length=30, null=True)),
                ('AlternateMobileNumber', models.IntegerField(null=True)),
                ('ProfilePic', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.TextField(max_length=30, null=True)),
                ('startDate', models.DateField(max_length=12, null=True)),
                ('usercount', models.IntegerField(null=True)),
                ('createBy', models.IntegerField(null=True)),
                ('isActive', models.IntegerField(null=True)),
                ('AmountPerUser', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sarkriGhata', models.DecimalField(decimal_places=2, max_digits=8)),
                ('groupbiddingtype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mobilenumber', models.BigIntegerField()),
                ('UserName', models.TextField()),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mobilenumber', models.BigIntegerField()),
                ('UserName', models.TextField()),
                ('ActualAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('AmountPaid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('AmountDue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('startDate', models.DateField(max_length=12)),
                ('GroupMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.GroupMember')),
            ],
        ),
        migrations.CreateModel(
            name='GroupBidding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActualAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biddingAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biddingBY', models.TextField()),
                ('biddingbymobile', models.BigIntegerField()),
                ('IsSelect', models.IntegerField()),
                ('Cyclenumber', models.IntegerField()),
                ('CreateDate', models.DateField(max_length=12)),
                ('GroupMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.GroupMember')),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='AmountRecived',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ActualAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ActualRecived', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Cyclenumber', models.IntegerField()),
                ('RevicerName', models.TextField()),
                ('Recivermobile', models.BigIntegerField()),
                ('RecivedDate', models.DateField(max_length=12)),
                ('UserGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.UserGroup')),
            ],
        ),
    ]
